import { Corridor, Infrastructure, Layout, Property } from './types';

export const INFRA = {
  dtcp: { id: 'dtcp', name: 'DTCP Approved Layout', icon: '📐', category: 'Approvals' as const },
  rera: { id: 'rera', name: 'RERA Registered', icon: '🏛️', category: 'Approvals' as const },
  cmda: { id: 'cmda', name: 'CMDA Approved', icon: '📜', category: 'Approvals' as const },
  title: { id: 'title', name: 'Clear Marketable Title', icon: '✅', category: 'Approvals' as const },
  patta: { id: 'patta', name: 'Individual Patta', icon: '🗂️', category: 'Approvals' as const },
  roads: { id: 'roads', name: 'Blacktop Internal Roads', icon: '🛣️', category: 'Roads & Utilities' as const },
  drains: { id: 'drains', name: 'Storm Water Drains', icon: '💧', category: 'Roads & Utilities' as const },
  power: { id: 'power', name: 'Underground Power Cabling', icon: '⚡', category: 'Roads & Utilities' as const },
  streetlight: { id: 'streetlight', name: 'Solar Street Lighting', icon: '💡', category: 'Roads & Utilities' as const },
  water: { id: 'water', name: 'Water Pipeline Network', icon: '🚰', category: 'Roads & Utilities' as const },
  sewage: { id: 'sewage', name: 'Sewage Treatment Line', icon: '♻️', category: 'Roads & Utilities' as const },
  park: { id: 'park', name: 'Landscaped Central Park', icon: '🌳', category: 'Community' as const },
  avenue: { id: 'avenue', name: 'Avenue Tree Plantation', icon: '🌿', category: 'Community' as const },
  clubhouse: { id: 'clubhouse', name: 'Community Clubhouse', icon: '🏛️', category: 'Community' as const },
  play: { id: 'play', name: "Children's Play Area", icon: '🛝', category: 'Community' as const },
  jogging: { id: 'jogging', name: 'Jogging Track', icon: '🏃', category: 'Community' as const },
  compound: { id: 'compound', name: 'Compound Wall', icon: '🧱', category: 'Security' as const },
  gate: { id: 'gate', name: 'Access Controlled Gate', icon: '🚧', category: 'Security' as const },
  cctv: { id: 'cctv', name: 'CCTV Surveillance', icon: '📹', category: 'Security' as const },
  guard: { id: 'guard', name: '24/7 Security Cabin', icon: '🔒', category: 'Security' as const },
} satisfies Record<string, Infrastructure>;

export const LAND_PHOTOS = {
  meadow: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
  openField: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=1200&q=80',
  hills: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80',
  greenHills: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=1200&q=80',
  forest: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
  grove: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1200&q=80',
  woodland: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=1200&q=80',
  valley: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=1200&q=80',
  coast: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
  ridge: 'https://images.unsplash.com/photo-1476231682828-37e571bc172f?w=1200&q=80',
  lake: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&q=80',
  mist: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1200&q=80',
};

export const FALLBACK_PHOTO = LAND_PHOTOS.meadow;

/** Initial catalogue used to seed the database on first run; runtime reads come from the DB. */
export const SEED_PROPERTIES: Property[] = [
  {
    id: '1',
    slug: 'imperium-emerald-acres-sholinganallur',
    title: 'Imperium Emerald Acres',
    projectName: 'Imperium Emerald Acres',
    builder: 'Imperium Realtors',
    type: 'Plot',
    price: 48,
    priceLabel: '₹48 Lakhs',
    area: 1200,
    location: 'Sholinganallur, Chennai',
    corridor: 'OMR — IT Corridor',
    city: 'Chennai',
    address: 'Sholinganallur – Medavakkam Main Road, Sholinganallur, Chennai – 600119',
    coordinates: { lat: 12.9011, lng: 80.2283 },
    status: 'Ready to Register',
    possession: 'Immediate registration',
    description:
      'Imperium Emerald Acres is a 6.4-acre gated plot enclave sitting one signal away from the Sholinganallur IT junction. Every plot is DTCP approved with an individual patta, and the layout is handed over fully developed — 30ft and 40ft blacktop roads, underground power, piped water and storm water drains are already in the ground. You can start construction the week you register.',
    highlights: [
      'DTCP approved with individual patta for every plot',
      'One signal from Sholinganallur IT junction — 4 km of Tidel Park',
      'Fully developed: roads, underground power, water and drains complete',
      '30ft and 40ft blacktop internal roads with solar street lighting',
      'Loan pre-approved with SBI, HDFC and LIC Housing Finance',
    ],
    infrastructure: [INFRA.dtcp, INFRA.rera, INFRA.title, INFRA.patta, INFRA.roads, INFRA.power, INFRA.water, INFRA.drains, INFRA.streetlight, INFRA.park, INFRA.avenue, INFRA.compound, INFRA.gate, INFRA.guard],
    photos: [LAND_PHOTOS.meadow, LAND_PHOTOS.openField, LAND_PHOTOS.grove, LAND_PHOTOS.greenHills, LAND_PHOTOS.forest],
    videoUrl: 'https://www.youtube.com/embed/ScMzIvxBSi4',
    nearbyPlaces: [
      { name: 'Sholinganallur Metro (Phase 2)', type: 'Metro', distance: '1.5 km', duration: '5 min' },
      { name: 'Tidel Park OMR', type: 'IT Park', distance: '4.0 km', duration: '14 min' },
      { name: 'Velammal Vidyalaya', type: 'School', distance: '2.0 km', duration: '7 min' },
      { name: 'Gleneagles Global Health City', type: 'Hospital', distance: '3.5 km', duration: '12 min' },
      { name: 'Chennai International Airport', type: 'Airport', distance: '20 km', duration: '38 min' },
    ],
    priceBreakdown: [
      { label: 'Plot value (₹4,000 / sq.ft × 1,200)', amount: '₹48,00,000' },
      { label: 'Registration & stamp duty (7%)', amount: '₹3,36,000' },
      { label: 'Layout development charges', amount: '₹1,50,000' },
      { label: 'Documentation & legal', amount: '₹35,000' },
      { label: 'Total payable', amount: '₹53,21,000' },
    ],
    featured: true,
    newLaunch: false,
    createdAt: '2025-01-20',
    land: {
      use: 'Residential',
      approvals: ['DTCP', 'RERA'],
      approvalId: 'DTCP/CHN/1184/2024 · TN/29/Layout/0418/2024',
      pricePerSqft: 4000,
      totalPlots: 96,
      availablePlots: 23,
      roadWidth: '30 ft & 40 ft blacktop',
      facingOptions: ['East', 'North', 'West', 'North-East'],
      appreciation: '12–14% p.a. over the last 3 years',
      soil: 'Red loam, firm bearing capacity',
      waterSource: 'Borewell at 180 ft + metro water pipeline',
      loanEligible: true,
      gatedCommunity: true,
      units: [
        { id: 'ea-a12', number: 'A-12', area: 1200, dimensions: '30 × 40 ft', facing: 'East', corner: false, price: 48, priceLabel: '₹48.00 L', availability: 'Available' },
        { id: 'ea-a14', number: 'A-14', area: 1500, dimensions: '30 × 50 ft', facing: 'North', corner: true, price: 62, priceLabel: '₹62.00 L', availability: 'Available' },
        { id: 'ea-b03', number: 'B-03', area: 800, dimensions: '20 × 40 ft', facing: 'West', corner: false, price: 31, priceLabel: '₹31.20 L', availability: 'Available' },
        { id: 'ea-b09', number: 'B-09', area: 2400, dimensions: '40 × 60 ft', facing: 'North-East', corner: true, price: 100, priceLabel: '₹1.00 Cr', availability: 'On Hold' },
        { id: 'ea-c01', number: 'C-01', area: 1200, dimensions: '30 × 40 ft', facing: 'East', corner: false, price: 48, priceLabel: '₹48.00 L', availability: 'Sold' },
      ],
      documents: [
        { name: 'Parent document search', detail: '30-year title trace by panel advocate', verified: true },
        { name: 'DTCP layout approval', detail: 'DTCP/CHN/1184/2024', verified: true },
        { name: 'RERA registration', detail: 'TN/29/Layout/0418/2024', verified: true },
        { name: 'Individual patta', detail: 'Issued per plot at registration', verified: true },
        { name: 'Encumbrance certificate', detail: 'EC clear for 30 years', verified: true },
      ],
    },
  },

  {
    id: '2',
    slug: 'imperium-sapphire-gardens-tambaram',
    title: 'Imperium Sapphire Gardens',
    projectName: 'Imperium Sapphire Gardens',
    builder: 'Imperium Realtors',
    type: 'Plot',
    price: 36,
    priceLabel: '₹36 Lakhs',
    area: 1000,
    location: 'Tambaram East, Chennai',
    corridor: 'GST — Southern Corridor',
    city: 'Chennai',
    address: 'Mudichur Road, Tambaram East, Chennai – 600059',
    coordinates: { lat: 12.923, lng: 80.14 },
    status: 'Ready to Register',
    possession: 'Immediate registration',
    description:
      'Sapphire Gardens is built for first-time land buyers. Plots start at 800 sq.ft and the layout sits 2.5 km from Tambaram railway station, inside the catchment of the best schools and colleges in south Chennai. Ground water at this stretch is among the most dependable in the district, and the entire layout is ring-fenced with a compound wall.',
    highlights: [
      'Entry-level plots from ₹28 Lakhs — ideal first land purchase',
      '2.5 km from Tambaram railway station and GST Road',
      'Excellent ground water source — borewell yield tested at 4 inches',
      'Walking distance to MCC, Sacred Heart and Velammal campuses',
      'DTCP approved with compound wall on all four boundaries',
    ],
    infrastructure: [INFRA.dtcp, INFRA.title, INFRA.patta, INFRA.roads, INFRA.water, INFRA.drains, INFRA.streetlight, INFRA.avenue, INFRA.play, INFRA.compound, INFRA.gate],
    photos: [LAND_PHOTOS.openField, LAND_PHOTOS.meadow, LAND_PHOTOS.woodland, LAND_PHOTOS.grove],
    videoUrl: 'https://www.youtube.com/embed/ScMzIvxBSi4',
    nearbyPlaces: [
      { name: 'Tambaram Railway Station', type: 'Metro', distance: '2.5 km', duration: '8 min' },
      { name: 'GST Road (NH-45)', type: 'Highway', distance: '1.8 km', duration: '6 min' },
      { name: 'Madras Christian College', type: 'School', distance: '2.0 km', duration: '6 min' },
      { name: 'Hindu Mission Hospital', type: 'Hospital', distance: '3.0 km', duration: '10 min' },
      { name: 'Chennai International Airport', type: 'Airport', distance: '10 km', duration: '20 min' },
    ],
    priceBreakdown: [
      { label: 'Plot value (₹3,600 / sq.ft × 1,000)', amount: '₹36,00,000' },
      { label: 'Registration & stamp duty (7%)', amount: '₹2,52,000' },
      { label: 'Layout development charges', amount: '₹1,00,000' },
      { label: 'Documentation & legal', amount: '₹30,000' },
      { label: 'Total payable', amount: '₹39,82,000' },
    ],
    featured: true,
    newLaunch: false,
    createdAt: '2025-03-10',
    land: {
      use: 'Residential',
      approvals: ['DTCP'],
      approvalId: 'DTCP/CHN/0972/2023',
      pricePerSqft: 3600,
      totalPlots: 64,
      availablePlots: 18,
      roadWidth: '23 ft & 30 ft blacktop',
      facingOptions: ['East', 'West', 'South', 'North'],
      appreciation: '9–11% p.a. over the last 3 years',
      soil: 'Red soil with gravel sub-base',
      waterSource: 'Borewell at 140 ft, year-round yield',
      loanEligible: true,
      gatedCommunity: true,
      units: [
        { id: 'sg-a05', number: 'A-05', area: 800, dimensions: '20 × 40 ft', facing: 'East', corner: false, price: 28, priceLabel: '₹28.80 L', availability: 'Available' },
        { id: 'sg-a11', number: 'A-11', area: 1000, dimensions: '25 × 40 ft', facing: 'North', corner: false, price: 36, priceLabel: '₹36.00 L', availability: 'Available' },
        { id: 'sg-b02', number: 'B-02', area: 1200, dimensions: '30 × 40 ft', facing: 'West', corner: true, price: 45, priceLabel: '₹45.00 L', availability: 'Available' },
        { id: 'sg-b07', number: 'B-07', area: 1000, dimensions: '25 × 40 ft', facing: 'South', corner: false, price: 34, priceLabel: '₹34.20 L', availability: 'Sold' },
      ],
      documents: [
        { name: 'Parent document search', detail: '30-year title trace by panel advocate', verified: true },
        { name: 'DTCP layout approval', detail: 'DTCP/CHN/0972/2023', verified: true },
        { name: 'Individual patta', detail: 'Issued per plot at registration', verified: true },
        { name: 'Encumbrance certificate', detail: 'EC clear for 30 years', verified: true },
      ],
    },
  },

  {
    id: '3',
    slug: 'imperium-gold-coast-uthandi-ecr',
    title: 'Imperium Gold Coast',
    projectName: 'Imperium Gold Coast',
    builder: 'Imperium Realtors',
    type: 'Plot',
    price: 185,
    priceLabel: '₹1.85 Cr',
    area: 2400,
    location: 'Uthandi, ECR, Chennai',
    corridor: 'ECR — Coastal Belt',
    city: 'Chennai',
    address: 'Golden Beach Road, off ECR, Uthandi, Chennai – 600119',
    coordinates: { lat: 12.8308, lng: 80.2493 },
    status: 'New Launch',
    possession: 'Ready to build',
    description:
      'Twelve plots. Two hundred metres from the water. Gold Coast is the most exclusive address Imperium Realtors has released on the East Coast Road — an access-controlled enclave of large-format beachside plots intended for bespoke villas. Underground cabling, a private approach road and a 40ft boulevard mean nothing about the build will look like a suburb.',
    highlights: [
      'Only 12 plots in the entire enclave — sizes from 2,400 sq.ft',
      '200 metres from Uthandi beach, direct ECR access',
      'RERA and DTCP approved with underground cabling throughout',
      '40 ft palm-lined boulevard and private approach road',
      'Beachside land on ECR has appreciated 16% p.a. over 5 years',
    ],
    infrastructure: [INFRA.dtcp, INFRA.rera, INFRA.title, INFRA.patta, INFRA.roads, INFRA.power, INFRA.water, INFRA.drains, INFRA.streetlight, INFRA.sewage, INFRA.park, INFRA.avenue, INFRA.clubhouse, INFRA.compound, INFRA.gate, INFRA.cctv, INFRA.guard],
    photos: [LAND_PHOTOS.coast, LAND_PHOTOS.ridge, LAND_PHOTOS.lake, LAND_PHOTOS.meadow],
    videoUrl: 'https://www.youtube.com/embed/ScMzIvxBSi4',
    nearbyPlaces: [
      { name: 'Uthandi Beach', type: 'Beach', distance: '0.2 km', duration: '2 min' },
      { name: 'East Coast Road', type: 'Highway', distance: '0.4 km', duration: '2 min' },
      { name: 'Mayajaal Entertainment', type: 'Mall', distance: '3.0 km', duration: '8 min' },
      { name: 'Apollo Clinic ECR', type: 'Hospital', distance: '4.0 km', duration: '10 min' },
      { name: 'Chennai International Airport', type: 'Airport', distance: '26 km', duration: '45 min' },
    ],
    priceBreakdown: [
      { label: 'Plot value (₹7,700 / sq.ft × 2,400)', amount: '₹1,84,80,000' },
      { label: 'Registration & stamp duty (7%)', amount: '₹12,93,600' },
      { label: 'Premium infrastructure charges', amount: '₹5,00,000' },
      { label: 'Documentation & legal', amount: '₹60,000' },
      { label: 'Total payable', amount: '₹2,03,33,600' },
    ],
    featured: true,
    newLaunch: true,
    createdAt: '2025-06-15',
    land: {
      use: 'Residential',
      approvals: ['DTCP', 'RERA'],
      approvalId: 'DTCP/CHN/1402/2025 · TN/29/Layout/0551/2025',
      pricePerSqft: 7700,
      totalPlots: 12,
      availablePlots: 7,
      roadWidth: '40 ft boulevard',
      facingOptions: ['East', 'North-East', 'South-East'],
      appreciation: '15–16% p.a. over the last 5 years',
      soil: 'Coastal sandy loam, compacted sub-grade',
      waterSource: 'Dedicated bore + RO treatment plant',
      loanEligible: true,
      gatedCommunity: true,
      units: [
        { id: 'gc-01', number: 'GC-01', area: 2400, dimensions: '40 × 60 ft', facing: 'East', corner: true, price: 185, priceLabel: '₹1.85 Cr', availability: 'Available' },
        { id: 'gc-04', number: 'GC-04', area: 3000, dimensions: '50 × 60 ft', facing: 'North-East', corner: false, price: 231, priceLabel: '₹2.31 Cr', availability: 'Available' },
        { id: 'gc-06', number: 'GC-06', area: 2400, dimensions: '40 × 60 ft', facing: 'South-East', corner: false, price: 178, priceLabel: '₹1.78 Cr', availability: 'On Hold' },
        { id: 'gc-09', number: 'GC-09', area: 4000, dimensions: '50 × 80 ft', facing: 'East', corner: true, price: 320, priceLabel: '₹3.20 Cr', availability: 'Available' },
        { id: 'gc-11', number: 'GC-11', area: 2400, dimensions: '40 × 60 ft', facing: 'East', corner: false, price: 182, priceLabel: '₹1.82 Cr', availability: 'Sold' },
      ],
      documents: [
        { name: 'Parent document search', detail: '30-year title trace by panel advocate', verified: true },
        { name: 'DTCP layout approval', detail: 'DTCP/CHN/1402/2025', verified: true },
        { name: 'RERA registration', detail: 'TN/29/Layout/0551/2025', verified: true },
        { name: 'CRZ clearance', detail: 'Layout falls outside CRZ-III restricted zone', verified: true },
        { name: 'Encumbrance certificate', detail: 'EC clear for 30 years', verified: true },
      ],
    },
  },

  {
    id: '4',
    slug: 'imperium-green-meadows-thiruporur',
    title: 'Imperium Green Meadows',
    projectName: 'Imperium Green Meadows',
    builder: 'Imperium Realtors',
    type: 'Plot',
    price: 28,
    priceLabel: '₹28 Lakhs',
    area: 1200,
    location: 'Thiruporur, Chennai',
    corridor: 'OMR — IT Corridor',
    city: 'Chennai',
    address: 'Thiruporur – Kelambakkam Road, Thiruporur, Chennai – 603110',
    coordinates: { lat: 12.7256, lng: 80.1917 },
    status: 'New Launch',
    possession: 'Development complete by Mar 2026',
    description:
      'Green Meadows is the value play on the OMR extension. Land here is priced at a third of Sholinganallur while sitting on the same road, and the SIPCOT Phase 3 expansion plus the proposed peripheral ring road both land within 6 km. Launch pricing is held for the first 30 bookings.',
    highlights: [
      'Launch pricing from ₹2,350 / sq.ft — held for first 30 bookings',
      '6 km from SIPCOT Phase 3 and the proposed peripheral ring road',
      'DTCP approved layout with 100% clear title',
      'Sizes from 1,200 sq.ft to 2,400 sq.ft, all four facings available',
      'Payment plan across 12 months at zero interest',
    ],
    infrastructure: [INFRA.dtcp, INFRA.title, INFRA.patta, INFRA.roads, INFRA.water, INFRA.drains, INFRA.streetlight, INFRA.park, INFRA.avenue, INFRA.play, INFRA.compound, INFRA.gate],
    photos: [LAND_PHOTOS.greenHills, LAND_PHOTOS.valley, LAND_PHOTOS.openField, LAND_PHOTOS.meadow],
    nearbyPlaces: [
      { name: 'SIPCOT IT Park Phase 3', type: 'IT Park', distance: '6.0 km', duration: '14 min' },
      { name: 'Thiruporur Bus Terminus', type: 'Highway', distance: '1.2 km', duration: '4 min' },
      { name: 'Hindustan University', type: 'School', distance: '8.0 km', duration: '18 min' },
      { name: 'Chettinad Hospital Kelambakkam', type: 'Hospital', distance: '9.0 km', duration: '20 min' },
      { name: 'Chennai International Airport', type: 'Airport', distance: '38 km', duration: '55 min' },
    ],
    priceBreakdown: [
      { label: 'Plot value (₹2,350 / sq.ft × 1,200)', amount: '₹28,20,000' },
      { label: 'Registration & stamp duty (7%)', amount: '₹1,97,400' },
      { label: 'Layout development charges', amount: '₹90,000' },
      { label: 'Documentation & legal', amount: '₹25,000' },
      { label: 'Total payable', amount: '₹31,32,400' },
    ],
    featured: true,
    newLaunch: true,
    createdAt: '2025-08-01',
    land: {
      use: 'Residential',
      approvals: ['DTCP'],
      approvalId: 'DTCP/KAN/0318/2025',
      pricePerSqft: 2350,
      totalPlots: 120,
      availablePlots: 78,
      roadWidth: '30 ft blacktop',
      facingOptions: ['East', 'West', 'North', 'South'],
      appreciation: '16–18% p.a. projected on corridor expansion',
      soil: 'Red loam over hard rock strata',
      waterSource: 'Layout borewell network at 200 ft',
      loanEligible: true,
      gatedCommunity: true,
      units: [
        { id: 'gm-a02', number: 'A-02', area: 1200, dimensions: '30 × 40 ft', facing: 'East', corner: false, price: 28, priceLabel: '₹28.20 L', availability: 'Available' },
        { id: 'gm-a18', number: 'A-18', area: 1800, dimensions: '30 × 60 ft', facing: 'North', corner: true, price: 44, priceLabel: '₹44.00 L', availability: 'Available' },
        { id: 'gm-c04', number: 'C-04', area: 2400, dimensions: '40 × 60 ft', facing: 'West', corner: false, price: 56, priceLabel: '₹56.40 L', availability: 'Available' },
        { id: 'gm-d09', number: 'D-09', area: 1200, dimensions: '30 × 40 ft', facing: 'South', corner: false, price: 27, priceLabel: '₹27.00 L', availability: 'Available' },
      ],
      documents: [
        { name: 'Parent document search', detail: '30-year title trace by panel advocate', verified: true },
        { name: 'DTCP layout approval', detail: 'DTCP/KAN/0318/2025', verified: true },
        { name: 'Individual patta', detail: 'Issued per plot at registration', verified: true },
        { name: 'Encumbrance certificate', detail: 'EC clear for 30 years', verified: true },
      ],
    },
  },

  {
    id: '5',
    slug: 'imperium-orchard-farms-mahabalipuram',
    title: 'Imperium Orchard Farms',
    projectName: 'Imperium Orchard Farms',
    builder: 'Imperium Realtors',
    type: 'Plot',
    price: 42,
    priceLabel: '₹42 Lakhs',
    area: 4800,
    location: 'Mahabalipuram, Chengalpattu',
    corridor: 'ECR — Coastal Belt',
    city: 'Chengalpattu',
    address: 'Kadambadi Village, off ECR, Mahabalipuram – 603104',
    coordinates: { lat: 12.6208, lng: 80.1945 },
    status: 'Development in Progress',
    possession: 'Handover from Dec 2025',
    description:
      'Managed farmland, twenty minutes past Mahabalipuram. Each buyer gets a fenced quarter-acre with 40 mango and coconut saplings already planted, drip irrigation run to the plot, and an on-site team that maintains it for you. Weekend cottages are permitted within the sanctioned building envelope.',
    highlights: [
      'Quarter-acre farm plots (4,800 sq.ft) with 40 fruit saplings planted',
      'Drip irrigation and on-site maintenance team included for 3 years',
      'Weekend cottage permitted within sanctioned building envelope',
      'Fenced individual boundaries with farm gate access',
      '20 minutes from Mahabalipuram, 90 minutes from central Chennai',
    ],
    infrastructure: [INFRA.patta, INFRA.title, INFRA.roads, INFRA.water, INFRA.streetlight, INFRA.avenue, INFRA.compound, INFRA.gate, INFRA.guard],
    photos: [LAND_PHOTOS.grove, LAND_PHOTOS.forest, LAND_PHOTOS.woodland, LAND_PHOTOS.mist],
    videoUrl: 'https://www.youtube.com/embed/ScMzIvxBSi4',
    nearbyPlaces: [
      { name: 'Mahabalipuram Town', type: 'Highway', distance: '12 km', duration: '20 min' },
      { name: 'Kovalam Beach', type: 'Beach', distance: '18 km', duration: '28 min' },
      { name: 'ECR Toll Plaza', type: 'Highway', distance: '6.0 km', duration: '10 min' },
      { name: 'Chettinad Hospital', type: 'Hospital', distance: '24 km', duration: '35 min' },
      { name: 'Chennai International Airport', type: 'Airport', distance: '52 km', duration: '75 min' },
    ],
    priceBreakdown: [
      { label: 'Farm plot value (₹875 / sq.ft × 4,800)', amount: '₹42,00,000' },
      { label: 'Registration & stamp duty (7%)', amount: '₹2,94,000' },
      { label: 'Plantation & irrigation setup', amount: '₹1,80,000' },
      { label: 'Maintenance (3 years, prepaid)', amount: '₹1,08,000' },
      { label: 'Total payable', amount: '₹47,82,000' },
    ],
    featured: false,
    newLaunch: true,
    createdAt: '2025-05-05',
    land: {
      use: 'Farmland',
      approvals: ['Panchayat'],
      approvalId: 'Kadambadi Panchayat NOC 214/2025',
      pricePerSqft: 875,
      totalPlots: 48,
      availablePlots: 31,
      roadWidth: '20 ft gravel farm roads',
      facingOptions: ['East', 'West', 'North', 'South'],
      appreciation: '10–12% p.a. over the last 3 years',
      soil: 'Alluvial, tested suitable for horticulture',
      waterSource: 'Two shared farm borewells with drip network',
      loanEligible: false,
      gatedCommunity: true,
      units: [
        { id: 'of-f03', number: 'F-03', area: 4800, dimensions: '60 × 80 ft', facing: 'East', corner: false, price: 42, priceLabel: '₹42.00 L', availability: 'Available' },
        { id: 'of-f07', number: 'F-07', area: 7200, dimensions: '80 × 90 ft', facing: 'North', corner: true, price: 63, priceLabel: '₹63.00 L', availability: 'Available' },
        { id: 'of-f12', number: 'F-12', area: 4800, dimensions: '60 × 80 ft', facing: 'West', corner: false, price: 40, priceLabel: '₹40.80 L', availability: 'On Hold' },
      ],
      documents: [
        { name: 'Parent document search', detail: '30-year title trace by panel advocate', verified: true },
        { name: 'Panchayat layout NOC', detail: 'Kadambadi Panchayat NOC 214/2025', verified: true },
        { name: 'Individual patta', detail: 'Issued per farm plot at registration', verified: true },
        { name: 'Soil & water test report', detail: 'Horticulture suitability certified', verified: true },
      ],
    },
  },

  {
    id: '6',
    slug: 'imperium-metro-enclave-oragadam',
    title: 'Imperium Metro Enclave',
    projectName: 'Imperium Metro Enclave',
    builder: 'Imperium Realtors',
    type: 'Plot',
    price: 32,
    priceLabel: '₹32 Lakhs',
    area: 1500,
    location: 'Oragadam, Chennai',
    corridor: 'Oragadam — Industrial Belt',
    city: 'Chennai',
    address: 'Oragadam – Walajabad Road, Oragadam, Chennai – 602105',
    coordinates: { lat: 12.8093, lng: 79.9425 },
    status: 'Ready to Register',
    possession: 'Immediate registration',
    description:
      'Oragadam is where Chennai builds things — Renault-Nissan, Daimler, Royal Enfield and the Apollo Tyres plant are all inside a 10 km radius, and the workforce living there is growing faster than the housing stock. Metro Enclave is a DTCP approved layout aimed squarely at that demand: mid-size plots, tarred roads, and the Sriperumbudur–Oragadam expressway 4 km away.',
    highlights: [
      '10 km radius covers Renault-Nissan, Daimler and Royal Enfield plants',
      '4 km from the Sriperumbudur–Oragadam expressway',
      'DTCP approved, RERA registered, individual patta per plot',
      'Rental yield in the belt currently runs 4–5% on built houses',
      'Plot sizes 1,200–3,000 sq.ft suited to independent homes',
    ],
    infrastructure: [INFRA.dtcp, INFRA.rera, INFRA.title, INFRA.patta, INFRA.roads, INFRA.power, INFRA.water, INFRA.drains, INFRA.streetlight, INFRA.park, INFRA.compound, INFRA.gate, INFRA.cctv],
    photos: [LAND_PHOTOS.openField, LAND_PHOTOS.hills, LAND_PHOTOS.meadow, LAND_PHOTOS.greenHills],
    nearbyPlaces: [
      { name: 'Renault-Nissan Plant', type: 'IT Park', distance: '7.0 km', duration: '12 min' },
      { name: 'Oragadam Expressway', type: 'Highway', distance: '4.0 km', duration: '8 min' },
      { name: 'Sriperumbudur Town', type: 'Highway', distance: '14 km', duration: '22 min' },
      { name: 'Sri Balaji Medical College', type: 'Hospital', distance: '16 km', duration: '25 min' },
      { name: 'Chennai International Airport', type: 'Airport', distance: '42 km', duration: '60 min' },
    ],
    priceBreakdown: [
      { label: 'Plot value (₹2,150 / sq.ft × 1,500)', amount: '₹32,25,000' },
      { label: 'Registration & stamp duty (7%)', amount: '₹2,25,750' },
      { label: 'Layout development charges', amount: '₹1,10,000' },
      { label: 'Documentation & legal', amount: '₹28,000' },
      { label: 'Total payable', amount: '₹35,88,750' },
    ],
    featured: false,
    newLaunch: false,
    createdAt: '2025-02-14',
    land: {
      use: 'Residential',
      approvals: ['DTCP', 'RERA'],
      approvalId: 'DTCP/KAN/0844/2024 · TN/29/Layout/0463/2024',
      pricePerSqft: 2150,
      totalPlots: 84,
      availablePlots: 29,
      roadWidth: '30 ft blacktop',
      facingOptions: ['East', 'West', 'North', 'South', 'North-West'],
      appreciation: '13–15% p.a. over the last 3 years',
      soil: 'Red gravel, high load bearing',
      waterSource: 'Layout borewell at 220 ft + overhead tank',
      loanEligible: true,
      gatedCommunity: true,
      units: [
        { id: 'me-a07', number: 'A-07', area: 1500, dimensions: '30 × 50 ft', facing: 'East', corner: false, price: 32, priceLabel: '₹32.25 L', availability: 'Available' },
        { id: 'me-b01', number: 'B-01', area: 3000, dimensions: '50 × 60 ft', facing: 'North-West', corner: true, price: 67, priceLabel: '₹67.00 L', availability: 'Available' },
        { id: 'me-b14', number: 'B-14', area: 1200, dimensions: '30 × 40 ft', facing: 'South', corner: false, price: 25, priceLabel: '₹25.80 L', availability: 'Available' },
        { id: 'me-c06', number: 'C-06', area: 1500, dimensions: '30 × 50 ft', facing: 'West', corner: false, price: 31, priceLabel: '₹31.50 L', availability: 'Sold' },
      ],
      documents: [
        { name: 'Parent document search', detail: '30-year title trace by panel advocate', verified: true },
        { name: 'DTCP layout approval', detail: 'DTCP/KAN/0844/2024', verified: true },
        { name: 'RERA registration', detail: 'TN/29/Layout/0463/2024', verified: true },
        { name: 'Encumbrance certificate', detail: 'EC clear for 30 years', verified: true },
      ],
    },
  },

  {
    id: '7',
    slug: 'imperium-riverside-park-thirumazhisai',
    title: 'Imperium Riverside Park',
    projectName: 'Imperium Riverside Park',
    builder: 'Imperium Realtors',
    type: 'Plot',
    price: 40,
    priceLabel: '₹40 Lakhs',
    area: 1200,
    location: 'Thirumazhisai, Chennai',
    corridor: 'Bangalore Highway — Western Corridor',
    city: 'Chennai',
    address: 'Chennai–Bangalore Highway (NH-48), Thirumazhisai, Chennai – 600124',
    coordinates: { lat: 13.0512, lng: 80.0374 },
    status: 'Development in Progress',
    possession: 'Development complete by Jun 2026',
    description:
      'Riverside Park sits on the western approach to Chennai, minutes from the Thirumazhisai bypass and the upcoming metro Phase 2 terminal at Poonamallee. The layout is CMDA approved — a stricter standard than DTCP, and the reason bank sanctions here close faster than anywhere else in our portfolio.',
    highlights: [
      'CMDA approved — the strictest layout standard in the metro area',
      '3 km from the Poonamallee metro Phase 2 terminal',
      'Direct access to NH-48 Chennai–Bangalore Highway',
      'Clubhouse and central park included in the layout handover',
      'Bank sanction typically closes in 7 working days',
    ],
    infrastructure: [INFRA.cmda, INFRA.rera, INFRA.title, INFRA.patta, INFRA.roads, INFRA.power, INFRA.water, INFRA.drains, INFRA.sewage, INFRA.streetlight, INFRA.park, INFRA.clubhouse, INFRA.jogging, INFRA.avenue, INFRA.compound, INFRA.gate, INFRA.cctv, INFRA.guard],
    photos: [LAND_PHOTOS.lake, LAND_PHOTOS.meadow, LAND_PHOTOS.valley, LAND_PHOTOS.grove],
    videoUrl: 'https://www.youtube.com/embed/ScMzIvxBSi4',
    nearbyPlaces: [
      { name: 'Poonamallee Metro (Phase 2)', type: 'Metro', distance: '3.0 km', duration: '8 min' },
      { name: 'NH-48 Bangalore Highway', type: 'Highway', distance: '1.0 km', duration: '3 min' },
      { name: 'Velammal Vidyalaya Mogappair', type: 'School', distance: '9.0 km', duration: '18 min' },
      { name: 'Sri Ramachandra Medical Centre', type: 'Hospital', distance: '11 km', duration: '20 min' },
      { name: 'Chennai International Airport', type: 'Airport', distance: '22 km', duration: '40 min' },
    ],
    priceBreakdown: [
      { label: 'Plot value (₹3,333 / sq.ft × 1,200)', amount: '₹40,00,000' },
      { label: 'Registration & stamp duty (7%)', amount: '₹2,80,000' },
      { label: 'Layout development charges', amount: '₹1,40,000' },
      { label: 'Clubhouse corpus (one time)', amount: '₹75,000' },
      { label: 'Total payable', amount: '₹44,95,000' },
    ],
    featured: false,
    newLaunch: false,
    createdAt: '2025-04-22',
    land: {
      use: 'Residential',
      approvals: ['CMDA', 'RERA'],
      approvalId: 'CMDA/LO/0233/2024 · TN/29/Layout/0487/2024',
      pricePerSqft: 3333,
      totalPlots: 108,
      availablePlots: 41,
      roadWidth: '33 ft & 40 ft blacktop',
      facingOptions: ['East', 'West', 'North', 'South', 'North-East'],
      appreciation: '11–13% p.a. over the last 3 years',
      soil: 'Clay loam with engineered sub-base',
      waterSource: 'Metro water connection + layout borewell',
      loanEligible: true,
      gatedCommunity: true,
      units: [
        { id: 'rp-a09', number: 'A-09', area: 1200, dimensions: '30 × 40 ft', facing: 'East', corner: false, price: 40, priceLabel: '₹40.00 L', availability: 'Available' },
        { id: 'rp-b05', number: 'B-05', area: 1600, dimensions: '40 × 40 ft', facing: 'North-East', corner: true, price: 56, priceLabel: '₹56.00 L', availability: 'Available' },
        { id: 'rp-c11', number: 'C-11', area: 2000, dimensions: '40 × 50 ft', facing: 'North', corner: false, price: 66, priceLabel: '₹66.60 L', availability: 'On Hold' },
        { id: 'rp-d02', number: 'D-02', area: 1200, dimensions: '30 × 40 ft', facing: 'West', corner: false, price: 38, priceLabel: '₹38.40 L', availability: 'Available' },
      ],
      documents: [
        { name: 'Parent document search', detail: '30-year title trace by panel advocate', verified: true },
        { name: 'CMDA layout approval', detail: 'CMDA/LO/0233/2024', verified: true },
        { name: 'RERA registration', detail: 'TN/29/Layout/0487/2024', verified: true },
        { name: 'Encumbrance certificate', detail: 'EC clear for 30 years', verified: true },
      ],
    },
  },

  {
    id: '8',
    slug: 'imperium-business-quarter-perungudi',
    title: 'Imperium Business Quarter',
    projectName: 'Imperium Business Quarter',
    builder: 'Imperium Realtors',
    type: 'Plot',
    price: 240,
    priceLabel: '₹2.40 Cr',
    area: 3000,
    location: 'Perungudi, Chennai',
    corridor: 'OMR — IT Corridor',
    city: 'Chennai',
    address: 'Thoraipakkam–Pallavaram Radial Road, Perungudi, Chennai – 600096',
    coordinates: { lat: 12.9508, lng: 80.2467 },
    status: 'Ready to Register',
    possession: 'Immediate registration',
    description:
      'Commercial land on the Radial Road, zoned and approved for mixed commercial use. These are corner-heavy plots with 40ft frontage designed for showrooms, clinics, coworking or small office blocks — the kind of stock that almost never comes to market on this stretch. CMDA approved with commercial land-use conversion already completed.',
    highlights: [
      'Commercial land use approved — no conversion needed',
      '40 ft road frontage on the Thoraipakkam–Pallavaram Radial Road',
      'Suited to showrooms, clinics, coworking and small office blocks',
      'Daily traffic count on the radial road exceeds 60,000 vehicles',
      'CMDA approved with clear commercial FSI of 2.0',
    ],
    infrastructure: [INFRA.cmda, INFRA.title, INFRA.patta, INFRA.roads, INFRA.power, INFRA.water, INFRA.drains, INFRA.sewage, INFRA.streetlight, INFRA.compound, INFRA.cctv],
    photos: [LAND_PHOTOS.hills, LAND_PHOTOS.openField, LAND_PHOTOS.meadow],
    nearbyPlaces: [
      { name: 'Perungudi Metro (Phase 2)', type: 'Metro', distance: '1.4 km', duration: '5 min' },
      { name: 'Olympia Tech Park', type: 'IT Park', distance: '1.2 km', duration: '4 min' },
      { name: 'Vivira Mall', type: 'Mall', distance: '2.5 km', duration: '8 min' },
      { name: 'Kauvery Hospital', type: 'Hospital', distance: '3.0 km', duration: '10 min' },
      { name: 'Chennai International Airport', type: 'Airport', distance: '14 km', duration: '28 min' },
    ],
    priceBreakdown: [
      { label: 'Plot value (₹8,000 / sq.ft × 3,000)', amount: '₹2,40,00,000' },
      { label: 'Registration & stamp duty (7%)', amount: '₹16,80,000' },
      { label: 'Infrastructure & frontage charges', amount: '₹6,00,000' },
      { label: 'Documentation & legal', amount: '₹80,000' },
      { label: 'Total payable', amount: '₹2,63,60,000' },
    ],
    featured: false,
    newLaunch: false,
    createdAt: '2025-07-08',
    land: {
      use: 'Commercial',
      approvals: ['CMDA'],
      approvalId: 'CMDA/COM/0117/2025',
      pricePerSqft: 8000,
      totalPlots: 9,
      availablePlots: 4,
      roadWidth: '60 ft radial road frontage',
      facingOptions: ['East', 'North', 'North-East'],
      appreciation: '14–15% p.a. over the last 3 years',
      soil: 'Filled and compacted, engineered for commercial load',
      waterSource: 'Metro water + dedicated commercial bore',
      loanEligible: true,
      gatedCommunity: false,
      units: [
        { id: 'bq-01', number: 'BQ-01', area: 3000, dimensions: '40 × 75 ft', facing: 'East', corner: true, price: 240, priceLabel: '₹2.40 Cr', availability: 'Available' },
        { id: 'bq-03', number: 'BQ-03', area: 4500, dimensions: '60 × 75 ft', facing: 'North', corner: false, price: 352, priceLabel: '₹3.52 Cr', availability: 'Available' },
        { id: 'bq-06', number: 'BQ-06', area: 3000, dimensions: '40 × 75 ft', facing: 'North-East', corner: true, price: 246, priceLabel: '₹2.46 Cr', availability: 'On Hold' },
      ],
      documents: [
        { name: 'Parent document search', detail: '30-year title trace by panel advocate', verified: true },
        { name: 'CMDA commercial approval', detail: 'CMDA/COM/0117/2025', verified: true },
        { name: 'Land use conversion order', detail: 'Residential to commercial, completed', verified: true },
        { name: 'Encumbrance certificate', detail: 'EC clear for 30 years', verified: true },
      ],
    },
  },

  {
    id: '9',
    slug: 'imperium-serene-county-kelambakkam',
    title: 'Imperium Serene County',
    projectName: 'Imperium Serene County',
    builder: 'Imperium Realtors',
    type: 'Plot',
    price: 38,
    priceLabel: '₹38 Lakhs',
    area: 1350,
    location: 'Kelambakkam, Chennai',
    corridor: 'OMR — IT Corridor',
    city: 'Chennai',
    address: 'Kelambakkam – Vandalur Road, Kelambakkam, Chennai – 603103',
    coordinates: { lat: 12.7862, lng: 80.2199 },
    status: 'Ready to Register',
    possession: 'Immediate registration',
    description:
      'Serene County is a 4.2-acre layout on the Kelambakkam–Vandalur Road, inside the belt that serves the southern end of OMR. Chettinad Health City, Hindustan University and the SIPCOT campuses all sit within a fifteen minute drive, which is why resale here has stayed liquid even in slow years.',
    highlights: [
      'DTCP approved, 4.2-acre layout with 72 plots',
      '15 minutes from Chettinad Health City and SIPCOT campuses',
      'Resale liquidity among the strongest on the southern OMR belt',
      'Central park, jogging track and children’s play area',
      'Plot sizes from 1,200 to 2,700 sq.ft',
    ],
    infrastructure: [INFRA.dtcp, INFRA.rera, INFRA.title, INFRA.patta, INFRA.roads, INFRA.power, INFRA.water, INFRA.drains, INFRA.streetlight, INFRA.park, INFRA.jogging, INFRA.play, INFRA.avenue, INFRA.compound, INFRA.gate, INFRA.guard],
    photos: [LAND_PHOTOS.woodland, LAND_PHOTOS.grove, LAND_PHOTOS.meadow, LAND_PHOTOS.forest],
    nearbyPlaces: [
      { name: 'Chettinad Health City', type: 'Hospital', distance: '4.0 km', duration: '10 min' },
      { name: 'SIPCOT IT Park', type: 'IT Park', distance: '8.0 km', duration: '16 min' },
      { name: 'Hindustan University', type: 'School', distance: '6.0 km', duration: '12 min' },
      { name: 'Kelambakkam Junction', type: 'Highway', distance: '1.5 km', duration: '5 min' },
      { name: 'Chennai International Airport', type: 'Airport', distance: '32 km', duration: '48 min' },
    ],
    priceBreakdown: [
      { label: 'Plot value (₹2,815 / sq.ft × 1,350)', amount: '₹38,00,000' },
      { label: 'Registration & stamp duty (7%)', amount: '₹2,66,000' },
      { label: 'Layout development charges', amount: '₹1,20,000' },
      { label: 'Documentation & legal', amount: '₹28,000' },
      { label: 'Total payable', amount: '₹42,14,000' },
    ],
    featured: false,
    newLaunch: false,
    createdAt: '2024-12-02',
    land: {
      use: 'Residential',
      approvals: ['DTCP', 'RERA'],
      approvalId: 'DTCP/KAN/0691/2024 · TN/29/Layout/0402/2024',
      pricePerSqft: 2815,
      totalPlots: 72,
      availablePlots: 16,
      roadWidth: '30 ft & 33 ft blacktop',
      facingOptions: ['East', 'West', 'North', 'South-East'],
      appreciation: '12–13% p.a. over the last 3 years',
      soil: 'Red loam with gravel base',
      waterSource: 'Layout borewell at 190 ft + overhead tank',
      loanEligible: true,
      gatedCommunity: true,
      units: [
        { id: 'sc-a04', number: 'A-04', area: 1350, dimensions: '30 × 45 ft', facing: 'East', corner: false, price: 38, priceLabel: '₹38.00 L', availability: 'Available' },
        { id: 'sc-b08', number: 'B-08', area: 2700, dimensions: '45 × 60 ft', facing: 'North', corner: true, price: 78, priceLabel: '₹78.00 L', availability: 'Available' },
        { id: 'sc-c02', number: 'C-02', area: 1200, dimensions: '30 × 40 ft', facing: 'West', corner: false, price: 33, priceLabel: '₹33.80 L', availability: 'On Hold' },
        { id: 'sc-c10', number: 'C-10', area: 1350, dimensions: '30 × 45 ft', facing: 'South-East', corner: false, price: 36, priceLabel: '₹36.50 L', availability: 'Sold' },
      ],
      documents: [
        { name: 'Parent document search', detail: '30-year title trace by panel advocate', verified: true },
        { name: 'DTCP layout approval', detail: 'DTCP/KAN/0691/2024', verified: true },
        { name: 'RERA registration', detail: 'TN/29/Layout/0402/2024', verified: true },
        { name: 'Encumbrance certificate', detail: 'EC clear for 30 years', verified: true },
      ],
    },
  },

  {
    id: 'r1',
    slug: 'imperium-altura-omr',
    title: 'Imperium Altura',
    projectName: 'Imperium Altura',
    builder: 'Imperium Realtors',
    type: 'Apartment',
    bhk: 3,
    price: 125,
    priceLabel: '₹1.25 Cr',
    area: 1650,
    location: 'OMR, Chennai',
    corridor: 'OMR — IT Corridor',
    city: 'Chennai',
    address: 'Plot 42, OMR Road, Sholinganallur, Chennai – 600119',
    coordinates: { lat: 12.901, lng: 80.2279 },
    status: 'Ready to Register',
    possession: 'Immediate',
    description:
      'A luxury residential tower on the OMR skyline with 3 BHK apartments, Italian marble flooring and a rooftop infinity pool.',
    highlights: ['Rooftop infinity pool', 'Italian marble flooring', 'Smart home automation'],
    infrastructure: [INFRA.rera, INFRA.power, INFRA.water, INFRA.cctv, INFRA.guard],
    photos: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80'],
    nearbyPlaces: [{ name: 'Sholinganallur Metro', type: 'Metro', distance: '0.8 km', duration: '3 min' }],
    priceBreakdown: [{ label: 'Base price', amount: '₹1,25,00,000' }],
    featured: false,
    newLaunch: false,
    createdAt: '2024-01-15',
    floorPlans: [],
  },

  {
    id: 'r2',
    slug: 'imperium-villa-enclave-ecr',
    title: 'Imperium Villa Enclave',
    projectName: 'Imperium Villa Enclave',
    builder: 'Imperium Realtors',
    type: 'Villa',
    bhk: 4,
    price: 285,
    priceLabel: '₹2.85 Cr',
    area: 3200,
    location: 'ECR, Chennai',
    corridor: 'ECR — Coastal Belt',
    city: 'Chennai',
    address: 'ECR Road, Neelankarai, Chennai – 600041',
    coordinates: { lat: 12.9308, lng: 80.2493 },
    status: 'Ready to Register',
    possession: 'Immediate',
    description: 'Sea-facing 4 BHK villas with private pools inside a gated community of 24 residences.',
    highlights: ['Private swimming pool per villa', 'Direct sea view', 'Only 24 villas'],
    infrastructure: [INFRA.rera, INFRA.power, INFRA.water, INFRA.gate, INFRA.guard],
    photos: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80'],
    nearbyPlaces: [{ name: 'Neelankarai Beach', type: 'Beach', distance: '0.2 km', duration: '1 min' }],
    priceBreakdown: [{ label: 'Base price', amount: '₹2,85,00,000' }],
    featured: false,
    newLaunch: false,
    createdAt: '2024-01-05',
    floorPlans: [],
  },
];

export const corridors: Corridor[] = [
  {
    id: 'c1',
    name: 'OMR — IT Corridor',
    slug: 'omr',
    blurb:
      'The Rajiv Gandhi Salai stretch from Perungudi to Thiruporur. Chennai’s densest concentration of IT employment, and the corridor where plot demand is most consistent.',
    image: LAND_PHOTOS.meadow,
    startingPrice: '₹2,350 / sq.ft',
    appreciation: '12–18% p.a.',
    drivers: ['SIPCOT Phase 3 expansion', 'Metro Phase 2 alignment', '4.5 lakh IT workforce'],
  },
  {
    id: 'c2',
    name: 'ECR — Coastal Belt',
    slug: 'ecr',
    blurb:
      'East Coast Road from Uthandi down to Mahabalipuram. Scarce coastal land, weekend-home demand and the highest per-square-foot values in our portfolio.',
    image: LAND_PHOTOS.coast,
    startingPrice: '₹875 / sq.ft',
    appreciation: '10–16% p.a.',
    drivers: ['Limited coastal supply', 'Tourism and weekend homes', 'ECR six-laning'],
  },
  {
    id: 'c3',
    name: 'GST — Southern Corridor',
    slug: 'gst',
    blurb:
      'Tambaram, Mudichur and Guduvancheri along NH-45. Established infrastructure, suburban rail, and the most affordable approved land inside the city limits.',
    image: LAND_PHOTOS.openField,
    startingPrice: '₹3,600 / sq.ft',
    appreciation: '9–11% p.a.',
    drivers: ['Suburban rail network', 'Education cluster', 'Airport proximity'],
  },
  {
    id: 'c4',
    name: 'Oragadam — Industrial Belt',
    slug: 'oragadam',
    blurb:
      'Chennai’s automotive manufacturing hub. Renault-Nissan, Daimler and Royal Enfield anchor a workforce that keeps outgrowing local housing supply.',
    image: LAND_PHOTOS.hills,
    startingPrice: '₹2,150 / sq.ft',
    appreciation: '13–15% p.a.',
    drivers: ['Auto manufacturing cluster', 'Oragadam expressway', 'Workforce housing gap'],
  },
  {
    id: 'c5',
    name: 'Bangalore Highway — Western Corridor',
    slug: 'nh48',
    blurb:
      'Poonamallee and Thirumazhisai on NH-48. CMDA-approved layouts, the Phase 2 metro terminal and the fastest bank sanctions of any corridor we sell.',
    image: LAND_PHOTOS.lake,
    startingPrice: '₹3,333 / sq.ft',
    appreciation: '11–13% p.a.',
    drivers: ['Metro Phase 2 terminal', 'NH-48 access', 'CMDA approved stock'],
  },
];

export const SEED_LAYOUTS: Layout[] = [
  {
    id: 'l1',
    name: 'Imperium Emerald Acres',
    builder: 'Imperium Realtors',
    location: 'Sholinganallur, Chennai',
    category: 'Plot',
    status: 'Development in Progress',
    totalPlots: 96,
    landArea: '6.4 acres',
    startingPrice: '₹31.2 L',
    completionDate: 'Handover complete',
    description:
      'A 6.4-acre gated enclave one signal from the Sholinganallur IT junction. Phase 1 sold out in eleven weeks; 23 plots remain in Phase 2 with roads, power and water already in the ground.',
    coverImage: LAND_PHOTOS.meadow,
    features: ['DTCP & RERA', '96 plots', '40 ft boulevard', 'Gated with security'],
  },
  {
    id: 'l2',
    name: 'Imperium Gold Coast',
    builder: 'Imperium Realtors',
    location: 'Uthandi, ECR, Chennai',
    category: 'Plot',
    status: 'New Launch',
    totalPlots: 12,
    landArea: '2.1 acres',
    startingPrice: '₹1.78 Cr',
    completionDate: 'Ready to build',
    description:
      'Twelve beachside plots, two hundred metres from the water, released as a single phase. The most exclusive land Imperium Realtors has brought to the East Coast Road.',
    coverImage: LAND_PHOTOS.coast,
    features: ['12 plots only', 'RERA & DTCP', 'Underground cabling', '200 m from beach'],
  },
  {
    id: 'l3',
    name: 'Imperium Green Meadows',
    builder: 'Imperium Realtors',
    location: 'Thiruporur, Chennai',
    category: 'Plot',
    status: 'New Launch',
    totalPlots: 120,
    landArea: '8.8 acres',
    startingPrice: '₹27.0 L',
    completionDate: 'March 2026',
    description:
      'The value play on the OMR extension — launch pricing at ₹2,350 per square foot, held for the first thirty bookings, with SIPCOT Phase 3 landing six kilometres away.',
    coverImage: LAND_PHOTOS.greenHills,
    features: ['Launch pricing', '120 plots', '12-month payment plan', 'DTCP approved'],
  },
  {
    id: 'l4',
    name: 'Imperium Riverside Park',
    builder: 'Imperium Realtors',
    location: 'Thirumazhisai, Chennai',
    category: 'Plot',
    status: 'Development in Progress',
    totalPlots: 108,
    landArea: '7.5 acres',
    startingPrice: '₹38.4 L',
    completionDate: 'June 2026',
    description:
      'CMDA approved land on the western approach, three kilometres from the Poonamallee metro terminal, delivered with a clubhouse and central park.',
    coverImage: LAND_PHOTOS.lake,
    features: ['CMDA approved', 'Clubhouse', '108 plots', 'Metro 3 km'],
  },
  {
    id: 'l5',
    name: 'Imperium Anna Nagar Heights',
    builder: 'Imperium Realtors',
    location: 'Anna Nagar, Chennai',
    category: 'Apartment',
    status: 'Fully Sold',
    totalPlots: 180,
    landArea: '3.2 acres',
    startingPrice: '₹75 L',
    completionDate: 'Completed 2023',
    description: 'A completed residential landmark in Anna Nagar delivering 180 apartments across two towers.',
    coverImage: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80',
    features: ['180 units', 'Fully sold', 'Completed 2023'],
  },
];

